# Comprehensive List of Indian Stock Symbols (NSE Tickers on Yahoo Finance ending with .NS)
# Categorized into Large Cap, Mid Cap, Small Cap, and F&O Futures

LARGE_CAP_SYMBOLS = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "BHARTIARTL.NS", "SBIN.NS", "ITC.NS", "LT.NS", "HCLTECH.NS",
    "KOTAKBANK.NS", "M&M.NS", "AXISBANK.NS", "SUNPHARMA.NS", "TITAN.NS",
    "MARUTI.NS", "ULTRACEMCO.NS", "ASIANPAINT.NS", "NTPC.NS", "POWERGRID.NS",
    "TATASTEEL.NS", "BAJFINANCE.NS", "ADANIENT.NS", "COALINDIA.NS", "ONGC.NS",
    "JSWSTEEL.NS", "GRASIM.NS", "HDFCLIFE.NS", "TECHM.NS", "WIPRO.NS",
    "HINDUNILVR.NS", "NESTLEIND.NS", "DRREDDY.NS", "CIPLA.NS",
    "APOLLOHOSP.NS", "EICHERMOT.NS", "BPCL.NS", "BEL.NS", "DIVISLAB.NS",
    "HEROMOTOCO.NS", "SHRIRAMFIN.NS", "TRENT.NS", "INDUSINDBK.NS",
    "BAJAJ-AUTO.NS", "ADANIPORTS.NS", "BRITANNIA.NS", "BAJAJFINSV.NS", "TATACONSUM.NS",
    "TATAMOTORS.NS", "SBILIFE.NS", "ADANIGREEN.NS", "ADANIPOWER.NS", "ATGL.NS",
    "AMBUJACEM.NS", "AUROPHARMA.NS", "BANKBARODA.NS", "BERGEPAINT.NS", "BOSCHLTD.NS",
    "CANBK.NS", "CHOLAFIN.NS", "COLPAL.NS", "DABUR.NS", "DLF.NS",
    "GAIL.NS", "GODREJCP.NS", "HAVELLS.NS", "HAL.NS", "ICICIGI.NS",
    "ICICIPRULI.NS", "INDIGO.NS", "IOC.NS", "IRFC.NS", "JIOFIN.NS",
    "JSWENERGY.NS", "LODHA.NS", "LTI.NS", "LTIM.NS", "LUPIN.NS",
    "MARICO.NS", "MOTHERSON.NS", "MUTHOOTFIN.NS", "NAUKRI.NS", "NHPC.NS",
    "NMDC.NS", "PFC.NS", "PIDILITIND.NS", "PNB.NS", "REC.NS",
    "RECLTD.NS", "SIEMENS.NS", "SRF.NS", "TVSMOTOR.NS", "UNITDSPR.NS",
    "VBL.NS", "VEDL.NS", "ZOMATO.NS", "ZYDUSLIFE.NS", "BHEL.NS"
]

MID_CAP_SYMBOLS = [
    "ABB.NS", "ACC.NS", "AUBANK.NS", "BALKRISIND.NS", "BANDHANBNK.NS",
    "BDL.NS", "BHARATFORG.NS", "BSE.NS", "CGPOWER.NS", "COFORGE.NS",
    "CONCOR.NS", "CUMMINSIND.NS", "DELHIVERY.NS", "DIXON.NS", "FEDERALBNK.NS",
    "FORTIS.NS", "GMRINFRA.NS", "GODREJPROP.NS", "GUJGASLTD.NS", "IDFCFIRSTB.NS",
    "IEX.NS", "IGL.NS", "INDHOTEL.NS", "INDUSTOWER.NS", "IPCALAB.NS",
    "JINDALSTEL.NS", "KALYANKJIL.NS", "KEI.NS", "LAURUSLABS.NS", "LTTS.NS",
    "MAXHEALTH.NS", "MAZDOCK.NS", "MPHASIS.NS", "MRF.NS", "NATIONALUM.NS",
    "NAVINFLUOR.NS", "NYKAA.NS", "OBEROIRLTY.NS", "OFSS.NS", "OIL.NS",
    "PAGEIND.NS", "PAYTM.NS", "PERSISTENT.NS", "POLYCAB.NS", "POONAWALLA.NS",
    "PVRINOX.NS", "SAIL.NS", "SOLARINDS.NS", "SUZLON.NS", "TATACOMM.NS",
    "TATAELXSI.NS", "TATAPOWER.NS", "TORNTPHARM.NS", "UPL.NS", "VOLTAS.NS",
    "YESBANK.NS", "AARTIIND.NS", "ABBOTINDIA.NS", "ABCAPITAL.NS", "ABFRL.NS",
    "ALKEM.NS", "AMATA.NS", "ANGELONE.NS", "APLLTD.NS", "APOLLOTYRE.NS",
    "ASHOKLEY.NS", "ASTRAL.NS", "ATUL.NS", "BATAINDIA.NS", "BHARATWIRE.NS",
    "BIOCON.NS", "BLUESTARCO.NS", "BSOFT.NS", "CENTURYTEX.NS", "CESC.NS",
    "CHAMBLFERT.NS", "CROMPTON.NS", "CYIENT.NS", "DALBHARAT.NS", "DEEPAKNTR.NS",
    "ESCORTS.NS", "EXIDEIND.NS", "FACT.NS", "GLENMARK.NS", "GMRAIRPORT.NS",
    "GNFC.NS", "GODREJIND.NS", "GRANULES.NS", "HDFCAMC.NS", "HONAUT.NS",
    "HUDCO.NS", "IDBI.NS", "INDIAMART.NS", "IRCTC.NS", "IREDA.NS",
    "JISLJALEQS.NS", "JKCEMENT.NS", "JSL.NS", "KPRMILL.NS", "LICHSGFIN.NS",
    "MANAPPURAM.NS", "MFSL.NS", "MGL.NS", "MOTILALOFS.NS", "MPHASIS.NS",
    "NATCOPHARM.NS", "NBCC.NS", "NLCINDIA.NS", "NMDC.NS", "NUVAMA.NS",
    "PETRONET.NS", "PFIZER.NS", "PHOENIXLTD.NS", "POLICYBZR.NS", "PRESTIGE.NS",
    "RAMCOCEM.NS", "RBLBANK.NS", "RELAXO.NS", "RVNL.NS", "SJVN.NS",
    "SKFINDIA.NS", "SONACOMS.NS", "SUNTV.NS", "SYNGENE.NS", "TATACHEM.NS"
]

SMALL_CAP_SYMBOLS = [
    "AARTIDRUGS.NS", "AARTISURF.NS", "ABSLAMC.NS", "AETHER.NS", "AFFLE.NS",
    "AGEISCHEM.NS", "ALOKINDS.NS", "AMRUTANJAN.NS", "ANANTRAJ.NS", "ANURAS.NS",
    "APTECHT.NS", "ASAHIINDIA.NS", "ASTERDM.NS", "ASTRAMICRO.NS", "AVANTIFEED.NS",
    "BAJAJELEC.NS", "BALAMINES.NS", "BALRAMCHIN.NS", "BEML.NS", "BHARATFORG.NS",
    "BIRLACORPN.NS", "BORORENEW.NS", "CAMPUS.NS", "CANFINHOME.NS", "CARBORUNIV.NS",
    "CARTRADE.NS", "CEATLTD.NS", "CENTURYPLY.NS", "CERA.NS", "CHALET.NS",
    "CHEMCON.NS", "CLEAN.NS", "COCHINSHIP.NS", "CRAFTMAN.NS", "DATAPATTNS.NS",
    "DCMSHRIRAM.NS", "DEEPAKFERT.NS", "DELTACORP.NS", "EASEMYTRIP.NS", "EIDPARRY.NS",
    "EQUITASBNK.NS", "ERIS.NS", "FDSE.NS", "FILATEX.NS", "FINPIPE.NS",
    "FIRSTSOURCE.NS", "FIVESTAR.NS", "GRAVITA.NS", "GREENPANEL.NS", "GRINDWELL.NS",
    "GSFC.NS", "HEG.NS", "HFCL.NS", "HIKAL.NS", "HIMATSEIDE.NS",
    "HINDCOPPER.NS", "HOMEFIRST.NS", "IBREALEST.NS", "INDIACEM.NS", "INDIAGLYCO.NS",
    "IONEXCHANG.NS", "ITDC.NS", "JAMNAAUTO.NS", "JBCHEPHARM.NS", "JKPAPER.NS",
    "JUSTDIAL.NS", "JYOTHYLAB.NS", "KAYNES.NS", "KFINTECH.NS", "KNRCON.NS",
    "KPITTECH.NS", "KRBL.NS", "KSB.NS", "LEMONTREE.NS", "LUXIND.NS", "MASTEK.NS",
    "METROPOLIS.NS", "MMTC.NS", "MOULDTEK.NS", "MTARTECH.NS", "NAZARA.NS",
    "NESCO.NS", "NOCIL.NS", "OLECTRA.NS", "PAISALO.NS", "POLYMED.NS",
    "PRAJIND.NS", "PRINCEPIPE.NS", "RAIN.NS", "RATNAMANI.NS", "RAYMOND.NS",
    "RCF.NS", "REDINGTON.NS", "ROUTE.NS", "SAFARI.NS", "SANGHIIND.NS",
    "SAPPHIRE.NS", "SBFC.NS", "SCHAEFFLER.NS", "SEQUENT.NS", "SHARDA CROP.NS",
    "SHOPERSTOP.NS", "SOBHA.NS", "SONATSOFTW.NS", "STARHEALTH.NS", "SUMICHEM.NS",
    "SUVENPHAR.NS", "SWANENERGY.NS", "SYRMA.NS", "TANLA.NS", "TATAINVEST.NS",
    "TEAMLEASE.NS", "TEJASNET.NS", "TRIDENT.NS", "TRITURBINE.NS", "UCOBANK.NS",
    "UJJIVANSFB.NS", "UTIAMC.NS", "VAIBHAVGBL.NS", "VAKRANGEE.NS", "VIPIND.NS",
    "WELCORP.NS", "WELSPUNLIV.NS", "WESTLIFE.NS", "ZENSARTECH.NS"
]

NIFTY_50_SYMBOLS = LARGE_CAP_SYMBOLS[:50]
NIFTY_FUTURES_SYMBOLS = list(dict.fromkeys(LARGE_CAP_SYMBOLS + MID_CAP_SYMBOLS[:50]))
NIFTY_ALL_SHARE_SYMBOLS = list(dict.fromkeys(LARGE_CAP_SYMBOLS + MID_CAP_SYMBOLS + SMALL_CAP_SYMBOLS))

COMPANY_NAMES = {
    "RELIANCE.NS": "Reliance Industries Ltd",
    "TCS.NS": "Tata Consultancy Services",
    "HDFCBANK.NS": "HDFC Bank Ltd",
    "INFY.NS": "Infosys Ltd",
    "ICICIBANK.NS": "ICICI Bank Ltd",
    "BHARTIARTL.NS": "Bharti Airtel Ltd",
    "SBIN.NS": "State Bank of India",
    "ITC.NS": "ITC Ltd",
    "LT.NS": "Larsen & Toubro Ltd",
    "HCLTECH.NS": "HCL Technologies",
    "KOTAKBANK.NS": "Kotak Mahindra Bank",
    "M&M.NS": "Mahindra & Mahindra",
    "AXISBANK.NS": "Axis Bank Ltd",
    "SUNPHARMA.NS": "Sun Pharma Ltd",
    "TITAN.NS": "Titan Company Ltd",
    "MARUTI.NS": "Maruti Suzuki India",
    "ULTRACEMCO.NS": "UltraTech Cement",
    "ASIANPAINT.NS": "Asian Paints Ltd",
    "NTPC.NS": "NTPC Ltd",
    "POWERGRID.NS": "Power Grid Corp",
    "TATASTEEL.NS": "Tata Steel Ltd",
    "BAJFINANCE.NS": "Bajaj Finance Ltd",
    "ADANIENT.NS": "Adani Enterprises",
    "COALINDIA.NS": "Coal India Ltd",
    "ONGC.NS": "Oil & Natural Gas Corp",
    "JSWSTEEL.NS": "JSW Steel Ltd",
    "GRASIM.NS": "Grasim Industries",
    "HDFCLIFE.NS": "HDFC Life Insurance",
    "TECHM.NS": "Tech Mahindra Ltd",
    "WIPRO.NS": "Wipro Ltd",
    "HINDUNILVR.NS": "Hindustan Unilever",
    "NESTLEIND.NS": "Nestle India Ltd",
    "DRREDDY.NS": "Dr. Reddy's Lab",
    "CIPLA.NS": "Cipla Ltd",
    "APOLLOHOSP.NS": "Apollo Hospitals",
    "EICHERMOT.NS": "Eicher Motors Ltd",
    "BPCL.NS": "Bharat Petroleum",
    "BEL.NS": "Bharat Electronics",
    "DIVISLAB.NS": "Divi's Laboratories",
    "HEROMOTOCO.NS": "Hero MotoCorp Ltd",
    "SHRIRAMFIN.NS": "Shriram Finance",
    "TRENT.NS": "Trent Ltd",
    "INDUSINDBK.NS": "IndusInd Bank",
    "BAJAJ-AUTO.NS": "Bajaj Auto Ltd",
    "ADANIPORTS.NS": "Adani Ports & SEZ",
    "BRITANNIA.NS": "Britannia Industries",
    "BAJAJFINSV.NS": "Bajaj Finserv Ltd",
    "TATACONSUM.NS": "Tata Consumer Products",
    "TATAMOTORS.NS": "Tata Motors Ltd",
    "SBILIFE.NS": "SBI Life Insurance",
    "ADANIGREEN.NS": "Adani Green Energy",
    "ADANIPOWER.NS": "Adani Power Ltd",
    "AMBUJACEM.NS": "Ambuja Cements",
    "AUROPHARMA.NS": "Aurobindo Pharma",
    "BANKBARODA.NS": "Bank of Baroda",
    "BERGEPAINT.NS": "Berger Paints",
    "BOSCHLTD.NS": "Bosch Ltd",
    "CANBK.NS": "Canara Bank",
    "CHOLAFIN.NS": "Cholamandalam Investment",
    "COLPAL.NS": "Colgate-Palmolive India",
    "DABUR.NS": "Dabur India Ltd",
    "DLF.NS": "DLF Ltd",
    "GAIL.NS": "GAIL (India) Ltd",
    "GODREJCP.NS": "Godrej Consumer Products",
    "HAVELLS.NS": "Havells India Ltd",
    "HAL.NS": "Hindustan Aeronautics",
    "ICICIGI.NS": "ICICI Lombard General Ins",
    "ICICIPRULI.NS": "ICICI Prudential Life Ins",
    "INDIGO.NS": "InterGlobe Aviation (IndiGo)",
    "IOC.NS": "Indian Oil Corp",
    "IRFC.NS": "Indian Railway Finance",
    "JIOFIN.NS": "Jio Financial Services",
    "JSWENERGY.NS": "JSW Energy Ltd",
    "LODHA.NS": "Macrotech Developers",
    "LTIM.NS": "LTIMindtree Ltd",
    "LUPIN.NS": "Lupin Ltd",
    "MARICO.NS": "Marico Ltd",
    "MOTHERSON.NS": "Samvardhana Motherson",
    "MUTHOOTFIN.NS": "Muthoot Finance Ltd",
    "NAUKRI.NS": "Info Edge (Naukri)",
    "NHPC.NS": "NHPC Ltd",
    "NMDC.NS": "NMDC Ltd",
    "PFC.NS": "Power Finance Corp",
    "PIDILITIND.NS": "Pidilite Industries",
    "PNB.NS": "Punjab National Bank",
    "RECLTD.NS": "REC Ltd",
    "SIEMENS.NS": "Siemens Ltd",
    "SRF.NS": "SRF Ltd",
    "TVSMOTOR.NS": "TVS Motor Company",
    "UNITDSPR.NS": "United Spirits Ltd",
    "VBL.NS": "Varun Beverages",
    "VEDL.NS": "Vedanta Ltd",
    "ZOMATO.NS": "Zomato Ltd",
    "ZYDUSLIFE.NS": "Zydus Lifesciences",
    "BHEL.NS": "Bharat Heavy Electricals",
    "ABB.NS": "ABB India Ltd",
    "ACC.NS": "ACC Ltd",
    "AUBANK.NS": "AU Small Finance Bank",
    "BALKRISIND.NS": "Balkrishna Industries",
    "BANDHANBNK.NS": "Bandhan Bank Ltd",
    "BDL.NS": "Bharat Dynamics Ltd",
    "BHARATFORG.NS": "Bharat Forge Ltd",
    "BSE.NS": "BSE Ltd",
    "CGPOWER.NS": "CG Power & Industrial",
    "COFORGE.NS": "Coforge Ltd",
    "CONCOR.NS": "Container Corp of India",
    "CUMMINSIND.NS": "Cummins India Ltd",
    "DELHIVERY.NS": "Delhivery Ltd",
    "DIXON.NS": "Dixon Technologies",
    "FEDERALBNK.NS": "Federal Bank Ltd",
    "FORTIS.NS": "Fortis Healthcare",
    "GMRINFRA.NS": "GMR Airports Infrastructure",
    "GODREJPROP.NS": "Godrej Properties",
    "GUJGASLTD.NS": "Gujarat Gas Ltd",
    "IDFCFIRSTB.NS": "IDFC First Bank",
    "IEX.NS": "Indian Energy Exchange",
    "IGL.NS": "Indraprastha Gas Ltd",
    "INDHOTEL.NS": "Indian Hotels Co",
    "INDUSTOWER.NS": "Indus Towers Ltd",
    "IPCALAB.NS": "IPCA Laboratories",
    "JINDALSTEL.NS": "Jindal Steel & Power",
    "KALYANKJIL.NS": "Kalyan Jewellers",
    "KEI.NS": "KEI Industries Ltd",
    "LAURUSLABS.NS": "Laurus Labs Ltd",
    "LTTS.NS": "L&T Technology Services",
    "MAXHEALTH.NS": "Max Healthcare Institute",
    "MAZDOCK.NS": "Mazagon Dock Shipbuilders",
    "MPHASIS.NS": "Mphasis Ltd",
    "MRF.NS": "MRF Ltd",
    "NATIONALUM.NS": "National Aluminium Co",
    "NAVINFLUOR.NS": "Navin Fluorine Intl",
    "NYKAA.NS": "FSN E-Commerce (Nykaa)",
    "OBEROIRLTY.NS": "Oberoi Realty Ltd",
    "OFSS.NS": "Oracle Financial Services",
    "OIL.NS": "Oil India Ltd",
    "PAGEIND.NS": "Page Industries Ltd",
    "PAYTM.NS": "One 97 Communications (Paytm)",
    "PERSISTENT.NS": "Persistent Systems",
    "POLYCAB.NS": "Polycab India Ltd",
    "POONAWALLA.NS": "Poonawalla Fincorp",
    "PVRINOX.NS": "PVR INOX Ltd",
    "SAIL.NS": "Steel Authority of India",
    "SOLARINDS.NS": "Solar Industries India",
    "SUZLON.NS": "Suzlon Energy Ltd",
    "TATACOMM.NS": "Tata Communications",
    "TATAELXSI.NS": "Tata Elxsi Ltd",
    "TATAPOWER.NS": "Tata Power Co Ltd",
    "TORNTPHARM.NS": "Torrent Pharmaceuticals",
    "UPL.NS": "UPL Ltd",
    "VOLTAS.NS": "Voltas Ltd",
    "YESBANK.NS": "Yes Bank Ltd",
    "ANGELONE.NS": "Angel One Ltd",
    "APOLLOTYRE.NS": "Apollo Tyres Ltd",
    "ASHOKLEY.NS": "Ashok Leyland Ltd",
    "ASTRAL.NS": "Astral Ltd",
    "BATAINDIA.NS": "Bata India Ltd",
    "BIOCON.NS": "Biocon Ltd",
    "CENTURYTEX.NS": "Century Textiles",
    "CESC.NS": "CESC Ltd",
    "CHAMBLFERT.NS": "Chambal Fertilisers",
    "CROMPTON.NS": "Crompton Greaves Consumer",
    "CYIENT.NS": "Cyient Ltd",
    "DALBHARAT.NS": "Dalmia Bharat Ltd",
    "DEEPAKNTR.NS": "Deepak Nitrite Ltd",
    "ESCORTS.NS": "Escorts Kubota Ltd",
    "EXIDEIND.NS": "Exide Industries",
    "GLENMARK.NS": "Glenmark Pharmaceuticals",
    "GNFC.NS": "Gujarat Narmada Valley",
    "GODREJIND.NS": "Godrej Industries",
    "GRANULES.NS": "Granules India Ltd",
    "HDFCAMC.NS": "HDFC Asset Management",
    "HONAUT.NS": "Honeywell Automation",
    "HUDCO.NS": "Housing & Urban Development",
    "INDIAMART.NS": "IndiaMART InterMESH",
    "IRCTC.NS": "Indian Railway Catering",
    "IREDA.NS": "Indian Renewable Energy",
    "JKCEMENT.NS": "JK Cement Ltd",
    "KPRMILL.NS": "K.P.R. Mill Ltd",
    "LICHSGFIN.NS": "LIC Housing Finance",
    "MANAPPURAM.NS": "Manappuram Finance",
    "MFSL.NS": "Max Financial Services",
    "MGL.NS": "Mahanagar Gas Ltd",
    "MOTILALOFS.NS": "Motilal Oswal Financial",
    "NATCOPHARM.NS": "Natco Pharma Ltd",
    "NBCC.NS": "NBCC (India) Ltd",
    "PETRONET.NS": "Petronet LNG Ltd",
    "PHOENIXLTD.NS": "Phoenix Mills Ltd",
    "POLICYBZR.NS": "PB Fintech (PolicyBazaar)",
    "PRESTIGE.NS": "Prestige Estates",
    "RAMCOCEM.NS": "The Ramco Cements",
    "RBLBANK.NS": "RBL Bank Ltd",
    "RELAXO.NS": "Relaxo Footwears",
    "RVNL.NS": "Rail Vikas Nigam Ltd",
    "SJVN.NS": "SJVN Ltd",
    "SKFINDIA.NS": "SKF India Ltd",
    "SONACOMS.NS": "Sona BLW Precision",
    "SUNTV.NS": "Sun TV Network",
    "SYNGENE.NS": "Syngene International",
    "TATACHEM.NS": "Tata Chemicals Ltd",
    "COCHINSHIP.NS": "Cochin Shipyard Ltd",
    "DATAPATTNS.NS": "Data Patterns (India)",
    "DEEPAKFERT.NS": "Deepak Fertilisers",
    "EASEMYTRIP.NS": "Easy Trip Planners",
    "EQUITASBNK.NS": "Equitas Small Finance Bank",
    "FIRSTSOURCE.NS": "Firstsource Solutions",
    "HEG.NS": "HEG Ltd",
    "HFCL.NS": "HFCL Ltd",
    "HINDCOPPER.NS": "Hindustan Copper",
    "JBCHEPHARM.NS": "JB Chemicals & Pharma",
    "JUSTDIAL.NS": "Just Dial Ltd",
    "KAYNES.NS": "Kaynes Technology",
    "KPITTECH.NS": "KPIT Technologies",
    "METROPOLIS.NS": "Metropolis Healthcare",
    "NAZARA.NS": "Nazara Technologies",
    "OLECTRA.NS": "Olectra Greentech",
    "PRAJIND.NS": "Praj Industries",
    "RAYMOND.NS": "Raymond Ltd",
    "REDINGTON.NS": "Redington Ltd",
    "SCHAEFFLER.NS": "Schaeffler India",
    "SOBHA.NS": "Sobha Ltd",
    "SONATSOFTW.NS": "Sonata Software",
    "STARHEALTH.NS": "Star Health Insurance",
    "SUMICHEM.NS": "Sumitomo Chemical",
    "TANLA.NS": "Tanla Platforms",
    "TEJASNET.NS": "Tejas Networks",
    "TRIDENT.NS": "Trident Ltd",
    "UCOBANK.NS": "UCO Bank",
    "UJJIVANSFB.NS": "Ujjivan Small Finance Bank",
    "VIPIND.NS": "VIP Industries",
    "ZENSARTECH.NS": "Zensar Technologies"
}
